### ISSUE TITLE
Vim todo + plugins

### ISSUE THREAD

**Issue by jaandrle** [jaandrle/dotfiles#9]
- [ ] Stylus
  - [ ] [iloginow/vim-stylus: A better vim plugin for stylus, including proper and up-to-date syntax highligting, indentation and autocomplete](https://github.com/iloginow/vim-stylus)
  - [ ] [sheerun/vim-polyglot: A solid language pack for Vim.](https://github.com/sheerun/vim-polyglot)
- [x] [Create custom source · neoclide/coc.nvim Wiki](https://github.com/neoclide/coc.nvim/wiki/Create-custom-source)
- [ ] coc-*: viml, svg
